### ISSUE TITLE
Bug - No Validation - mobile number

### ISSUE THREAD

**Issue by selvianu** [csys-fresher-batch-2021/groceryapp-core#1]
Scenario:
As a user, I can add only valid mobile numbers.

Bug: When I try to add a new customer, no validation for mobile number. It accepts any number of digits. (more than 10 digits and less than 10 digits)

![image](https://user-images.githubusercontent.com/22638364/126242496-71f794dc-4156-49ff-a2fa-f0de1dfbdbb1.png)

![image](https://user-images.githubusercontent.com/22638364/126242550-ab49c54b-1d47-4aa8-a403-ecc854c62297.png)

![image](https://user-images.githubusercontent.com/22638364/126243804-335e6795-8736-431e-afd6-a0ded1d7dc72.png)

**Comment by Rajesh18042** [comment]
will finish that issue mam please check it...
