### ISSUE TITLE
Bug - Feature - Checking customer

### ISSUE THREAD

**Issue by selvianu** [csys-fresher-batch-2021/groceryapp-core#2]
Scenario: When I try to check whether the customer is exiting customer or not,
Bug : When I give customer details, along with the status, it also displays all customers mobile number

![image](https://user-images.githubusercontent.com/22638364/126242821-d2d02527-a0f3-4514-8dd9-c7f0a0b46be3.png)

**Comment by Rajesh18042** [comment]
will finish that issue mam please check it...
