### ISSUE TITLE
Bug - No Validation - Price and Quantity

### ISSUE THREAD

**Issue by selvianu** [csys-fresher-batch-2021/groceryapp-core#4]
Scenario: When products are added into grocery, negative price and amount cannot be added
Bug: Products are added with negative price/cost and negative quantity.

![image](https://user-images.githubusercontent.com/22638364/126255420-7a190516-47e2-4003-9a78-5647a72ca90c.png)

**Comment by Rajesh18042** [comment]
will finish that issue mam please check it...
